# Generated by Django 3.2.7 on 2023-09-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('symptom', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('pname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=200)),
                ('starttime', models.CharField(max_length=200)),
                ('endtime', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
